import { JetBrains_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
<<<<<<< HEAD
import { Toaster } from '@/components/ui/toaster'
=======
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
>>>>>>> 1cba017 (Homepage)

const jetbrainsMono = JetBrains_Mono({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
	variable: '--font-jetbrainsMono',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<head>
				<title>Safe Bike </title>
			</head>
			<body className={jetbrainsMono.variable}>
				<Header />
<<<<<<< HEAD
				{children}
				<Toaster />
=======
				<Theme>
					{children}
				</Theme>
				
>>>>>>> 1cba017 (Homepage)
			</body>
		</html>
	)
}
